name: "check"
on:
  push:
  pull_request_target:
jobs:
  fmt:
    name: "nix fmt"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix fmt $(find ./ -regex './[^.]*\.nix') -- --check
  check:
    name: "nix flake check"
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: niri
    - run: nix flake check
  check-docs:
    name: "generated docs match"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: niri
    - run: |
        nix eval --raw .#lib.internal.docs-markdown > docs.fresh.md
        cat docs.fresh.md
        cat docs.md
        diff docs.md docs.fresh.md
